services:
  guarded-query-router:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONPATH=/app:/app/src
    network_mode: host